export enum Platform {
  ANDROID = "ANDROID",
  IOS = "IOS",
  WEB = "WEB",
}

export enum AdminVerificationStatus {
  REQUESTED = "REQUESTED",
  UNDER_REVIEW = "UNDER_REVIEW",
  APPROVED = "APPROVED",
  REJECTED = "REJECTED",
  RESUBMITTED = "RESUBMITTED",
  NOT_REQUESTED = "NOT_REQUESTED",
}

export enum AppointmentStatus {
  BOOKED = "BOOKED",
  COMPLETED = "COMPLETED",
  CANCELLED = "CANCELLED",
  REJECTED_BY_PROVIDER = "REJECTED_BY_PROVIDER",
  NOT_ATTENDED = "NOT_ATTENDED",
  CONFIRMED = "CONFIRMED",
  EXPIRED = "EXPIRED",
}

export enum Role {
  ADMIN = "ADMIN",
  USER = "USER",
  PROVIDER = "PROVIDER",
}

export enum AppConnect {
  GOOGLE_CALENDAR = "GOOGLE_CALENDAR",
  STRIPE = "STRIPE",
  NOTION = "NOTION",
  WHATSAPP = "WHATSAPP",
  RAZORPAY = "RAZORPAY",
  PAYPAL = "PAYPAL",
}

export enum OtpPurpose {
  REGISTRATION = "REGISTRATION",
  PASSWORD_RESET = "PASSWORD_RESET",
}

export enum PaymentFor {
  PROVIDER_SUBSCRIPTION = "PROVIDER_SUBSCRIPTION",
  APPOINTMENT_BOOKING = "APPOINTMENT_BOOKING",
  PROVIDER_PAYOUT = "PROVIDER_PAYOUT",
  CANCEL_BOOKING = "CANCEL_BOOKING",
  CANCEL_SUBSCRIPTION = "CANCEL_SUBSCRIPTION",
}

export enum PaymentStatus {
  PENDING = "PENDING",
  PAID = "PAID",
  FAILED = "FAILED",
  CANCELLED = "CANCELLED",
  REFUNDED = "REFUNDED",
}

export enum PlanName {
  TRIAL = "TRIAL",
  STARTER = "STARTER",
  PROFESSIONAL = "PROFESSIONAL",
  ENTERPRISE = "ENTERPRISE",
  NO_SUBSCRIPTION = "NO_SUBSCRIPTION",
}

export enum ServiceMode {
  ONLINE = "ONLINE",
  OFFLINE = "OFFLINE",
  BOTH = "BOTH",
}

export enum SubscriptionStatus {
  ACTIVE = "ACTIVE",
  CANCELLED = "CANCELLED",
  TRIALING = "TRIALING",
  PAST_DUE = "PAST_DUE",
  UNPAID = "UNPAID",
  INCOMPLETE = "INCOMPLETE",
  INCOMPLETE_EXPIRED = "INCOMPLETE_EXPIRED",
  EXPIRED = "EXPIRED",
  PAYMENT_FAILED = "PAYMENT_FAILED",
}

export enum EventStatus {
  SUCCESS = "SUCCESS",
  FAILED = "FAILED",
  PENDING = "PENDING",
  RETRY = "RETRY",
}

export enum PaymentAccountStatus {
  PENDING = "PENDING",
  ACTIVE = "ACTIVE",
  RESTRICTED = "RESTRICTED",
  REVOKED = "REVOKED",
  NOT_CONNECTED = "NOT_CONNECTED",
}

export enum IntegrationStatus {
  CONNECTED = "CONNECTED",
  EXPIRED = "EXPIRED",
  REVOKED = "REVOKED",
  DISCONNECTED = "DISCONNECTED",
}

export enum IntegrationProvider {
  GOOGLE = "GOOGLE",
  WHATSAPP = "WHATSAPP",
  NOTION = "NOTION",
  SLACK = "SLACK",
}

export enum NotificationChannel {
  EMAIL = "EMAIL",
  PUSH = "PUSH",
  IN_APP = "IN_APP",
  SMS = "SMS",
}

export enum NotificationType {
  ACCOUNT_ACTIVITY = "ACCOUNT_ACTIVITY",
  SYSTEM_UPDATES = "SYSTEM_UPDATES",
  PROMOTIONAL_UPDATES = "PROMOTIONAL_UPDATES",
}
